[platformio]
default_envs = nodemcu-32s

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  olikraus/U8g2@^2.35.30
  bblanchon/ArduinoJson@^7.0.4

[env:nodemcu-32s-ota]
extends = env:nodemcu-32s
upload_protocol = espota
upload_port = admin-dashboard.local
upload_flags =
  --auth=${sysenv.OTA_PASSWORD}

[env:oled-test]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -D OLED_DIAGNOSTIC_MODE

lib_deps =
  olikraus/U8g2@^2.35.30
  bblanchon/ArduinoJson@^7.0.4
